accounts/urls.py
from django.conf.urls import url
from . import views
from .forms import LoginForm

urlpatterns = [
    url(r'^login/$', views.LoginView.as_view(success_url='/'), name='login', kwargs={'authentication_form': LoginForm}),
    url(r'^register/$', views.RegisterView.as_view(success_url="/"), name='register'),
    url(r'^logout/$', views.LogoutView.as_view(), name='logout')
]

blog/urls.py
#!/usr/bin/env python
# encoding: utf-8


from django.conf.urls import url, include
from . import views

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^article/(?P<year>\d+)/(?P<month>\d+)/(?P<day>\d+)/(?P<article_id>\d+).html$',
        views.ArticleDetailView.as_view(),
        name='detailbyid'),
    url(r'^category/(?P<category_name>[\w-]+).html$', views.CategoryDetailView.as_view(), name='category_detail'),
    url(r'^search', include('haystack.urls'), name='search')
]

doudou_blog/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('blog.urls', namespace='blog', app_name='blog')),
    url(r'', include('comments.urls', namespace='comment', app_name='comments')),
    url(r'', include('accounts.urls', namespace='account', app_name='accounts')),

]

blog/models.py
from django.db import models
from uuslug import slugify
from django.contrib.sites.models import Site
from django.conf import settings
from django.core.urlresolvers import reverse
from doudou_blog.utils import cache


# 参考各类参数涵义:http://blog.csdn.net/devil_2009/article/details/41735611
# 参考内部类Meta:http://www.cnblogs.com/ccorz/p/Django-models-zhong-demeta-xuan-xiang.html


class BaseModel(models.Model):
    slug = models.SlugField(default='no-slug', max_length=60, blank=True)

    def save(self, *args, **kwargs):
        if not self.slug or self.slug == 'no-slug' or not self.id:
            slug = self.title if 'title' in self.__dict__ else self.name
            self.slug = slugify(slug)
        super().save(*args, **kwargs)

    def get_full_url(self):
        site = Site.objects.get_current().domain
        url = "https://{site}{path}".format(site=site, path=self.get_absolute_url)
        return url

    class Meta:
        abstract = True


class Article(BaseModel):
    """文章"""
    STATUS_CHOICES = (
        ('d', '草稿'),
        ('p', '发表'),
    )
    COMMENT_STATUS = (
        ('o', '打开'),
        ('c', '关闭'),
    )
    TYPE = (
        ('a', '文章'),
        ('p', '页面'),
    )
    title = models.CharField('标题', max_length=200, unique=True)
    body = models.TextField('正文')
    created_time = models.DateTimeField('创建时间', auto_now_add=True)
    last_mod_time = models.DateTimeField('修改时间', auto_now=True)
    pub_time = models.DateTimeField('发布时间', blank=True, null=True)
    status = models.CharField('文章状态', max_length=1, choices=STATUS_CHOICES, default='p')
    comment_status = models.CharField('评论状态', max_length=1, choices=COMMENT_STATUS, default='o')
    type = models.CharField('类型', max_length=1, choices=TYPE, default='a')
    views = models.PositiveIntegerField('浏览量', default=0)

    author = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='作者', on_delete=models.CASCADE)
    category = models.ForeignKey('Category', verbose_name='分类', on_delete=models.CASCADE, blank=True, null=True)
    tags = models.ManyToManyField('Tag', verbose_name='标签集合', blank=True)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-pub_time']
        verbose_name = "文章"
        verbose_name_plural = verbose_name
        get_latest_by = 'created_time'

    def viewed(self):
        self.views += 1
        self.save(update_fields=['views'])

    def get_absolute_url(self):
        return reverse('blog:detailbyid', kwargs={
            'article_id': self.id,
            'year': self.created_time.year,
            'month': self.created_time.month,
            'day': self.created_time.day
        })

    def comment_list(self):
        cache_key = 'article_comment_{id}'.format(id=self.id)
        value = cache.get(cache_key)
        if value:
            return value
        else:
            comments = self.comment_set.all()
            cache.set(cache_key, comments)
            return comments

    def get_admin_url(self):
        info = (self._meta.app_label, self._meta.model_name)
        return reverse('admin:%s_%s_change' % info, args=(self.pk,))

    def next_article(self):
        return Article.objects.filter(id__gt=self.id, status='p').order_by('id').first()

    def prev_article(self):
        return Article.objects.filter(id__lt=self.id, status='p').first()


class Category(BaseModel):
    """文章分类"""
    name = models.CharField('分类名', max_length=30, unique=True)
    created_time = models.DateTimeField('创建时间', auto_now_add=True)
    last_mod_time = models.DateTimeField('修改时间', auto_now=True)
    parent_category = models.ForeignKey('self', verbose_name='父类分类', blank=True, null=True)

    class Meta:
        ordering = ['name']
        verbose_name = '分类'
        verbose_name_plural = verbose_name

    def get_absolute_url(self):
        return reverse('blog:category_detail', kwargs={'category_name': self.slug})

    def __str__(self):
        return self.name

    def get_category_tree(self):
        """
        递归获得分类目录的父级
        :return:
        """
        categorys = []

        def parse(category):
            categorys.append(category)
            if category.parent_category:
                parse(category.parent_category)

        parse(self)
        return categorys

    def get_sub_categorys(self):
        """
        获得当前分类目录所有子集
        :return:
        """

        categorys = []
        all_categorys = Category.objects.all()

        def parse(category):
            if category not in categorys:
                categorys.append(category)
            childs = all_categorys.filter(parent_category=category)
            for chid in childs:
                if category not in categorys:
                    categorys.append(chid)
                parse(chid)

        parse(self)
        return categorys


class Tag(BaseModel):
    """文章标签"""
    name = models.CharField('标签名', max_length=30, unique=True)
    created_time = models.DateTimeField('创建时间', auto_now_add=True)
    last_mod_time = models.DateTimeField("修改时间", auto_now=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('blog:tag_detail', kwargs={'tag_name': self.slug})

    def get_article_count(self):
        return Article.objects.filter(tags__name=self.name).distinct().count()

    class Meta:
        ordering = ['name']
        verbose_name = '标签'
        verbose_name_plural = verbose_name

comments/models.py
from django.db import models
from django.conf import settings
from blog.models import Article
from django.contrib.sites.models import Site


# Create your models here.

class Comment(models.Model):
    body = models.TextField('正文', max_length=300)
    created_time = models.DateTimeField('创建时间', auto_now_add=True)
    last_mod_time = models.DateTimeField('修改时间', auto_now=True)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='作者', on_delete=models.CASCADE)
    article = models.ForeignKey(Article, verbose_name='文章', on_delete=models.CASCADE)
    parent_comment = models.ForeignKey('self', verbose_name='上级评论', blank=True, null=True)

    class Meta:
        ordering = ['created_time']
        verbose_name = '评论'
        verbose_name_plural = verbose_name
        get_latest_by = 'created_time'

    def send_comment_email(self, msg):
        try:
            msg.send()
        except:
            pass

    def __str__(self):
        return self.body

blog/views.py
from django.shortcuts import render
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.conf import settings
from doudou_blog.utils import cache, logger
from blog.models import Article, Category
from comments.forms import CommentForm
from django import forms
from django.shortcuts import get_object_or_404


# Create your views here.


class ArticleListView(ListView):
    template_name = 'blog/article_index.html'

    context_object_name = 'article_list'

    page_type = ''
    paginate_by = settings.PAGINATE_BY
    page_kwarg = 'page'

    def get_view_cache_key(self):
        return self.request.get['pages']

    @property
    def page_number(self):
        page_kwarg = self.page_kwarg
        page = self.kwargs.get(page_kwarg) or self.request.GET.get(page_kwarg) or 1
        return page

    def get_queryset_cache_key(self):
        """
        子类重写.获得queryset的缓存key
        """
        raise NotImplementedError

    def get_queryset_data(self):
        """
        子类重写.获取queryset的数据
        """
        raise NotImplementedError

    def get_queryset_from_cahe(self, cache_key):
        value = cache.get(cache_key)

        if value:
            logger.info('get view cache.key:{key}'.format(key=cache_key))
            return value
        else:
            article_list = self.get_queryset_data()
            cache.set(cache_key, article_list)
            logger.info('set view cache.key:{key}'.format(key=cache_key))
            return article_list

    def get_queryset(self):
        key = self.get_queryset_cache_key()
        value = self.get_queryset_from_cahe(key)
        return value


class IndexView(ArticleListView):
    def get_queryset_data(self):
        article_list = Article.objects.filter(type='a', status='p')
        return article_list

    def get_queryset_cache_key(self):
        cache_key = 'index_{page}'.format(page=self.page_number)
        return cache_key


class ArticleDetailView(DetailView):
    template_name = 'blog/article_detail.html'
    model = Article
    pk_url_kwarg = 'article_id'
    context_object_name = 'article'

    def get_object(self):
        obj = super(ArticleDetailView, self).get_object()
        obj.viewed()
        self.object = obj
        return obj

    def get_context_data(self, **kwargs):
        comment_form = CommentForm()
        user = self.request.user

        if user.is_authenticated and not user.is_anonymous and user.email and user.username:
            comment_form.fields.update({
                'email': forms.CharField(widget=forms.HiddenInput()),
                'name': forms.CharField(widget=forms.HiddenInput()),
            })
            comment_form.fields["email"].initial = user.email
            comment_form.fields["name"].initial = user.username

        article_comments = self.object.comment_list()

        kwargs['form'] = comment_form

        article_comments = self.object.comment_list()
        kwargs['article_comments'] = article_comments
        kwargs['comment_count'] = len(article_comments) if article_comments else 0
        kwargs['next_article'] = self.object.next_article
        kwargs['prev_article'] = self.object.prev_article
        return super(ArticleDetailView, self).get_context_data(**kwargs)


class CategoryDetailView(ArticleListView):
    page_type = "分类目录归档"

    def get_queryset_data(self):
        slug = self.kwargs['category_name']
        category = get_object_or_404(Category, slug=slug)
        categoryname = category.name

        self.categoryname = categoryname
        categorynames = list(map(lambda c: c.name, category.get_sub_categorys()))
        article_list = Article.objects.filter(category__name__in=categorynames, status='p')
        return article_list

    def get_queryset_cache_key(self):
        slug = self.kwargs['category_name']
        category = get_object_or_404(Category, slug=slug)
        categoryname = category.name
        self.categoryname = categoryname
        cache_key = 'category_list_{categoryname}_{page}'.format(categoryname=categoryname, page=self.page_number)
        return cache_key

    def get_context_data(self, **kwargs):

        categoryname = self.categoryname
        try:
            categoryname = categoryname.split('/')[-1]
        except:
            pass
        kwargs['page_type'] = CategoryDetailView.page_type
        kwargs['tag_name'] = categoryname
        return super(CategoryDetailView, self).get_context_data(**kwargs)

templates/blog/tags/article_info.html
{% load blog_tags %}
<article id="post-{{ article.pk }}">
    <header class="entry-header">
        <h1 class="entry-title">
            {% if isindex %}
                <a href="{{ article.get_absolute_url }}" rel="bookmark">
                    {{ article.title }}
                </a>
            {% else %}
                {{ article.title }}
            {% endif %}
        </h1>
        <div class="comments-link">
            {% if article.comment_status == "o" %}
                <a href="{{ article.get_absolute_url }}#comments" rel="nofollow">
                    {% if article.comment and article.comment_set.count %}
                        {{ article.comment_set.count }}个评论
                    {% else %}
                        发表评论
                    {% endif %}
                </a>

            {% endif %}
            <div style="float: right">
                {{ article.views }} views
            </div>
        </div>
        <br/>
    </header>
    {% if isindex %}
        {{ article.body|truncatechars_content|custom_markdown }}
        <p class="read-more"><a href="{{ article.get_absolute_url }}">Read more</a></p>
    {% else %}
        {{ article.body|custom_markdown }}
    {% endif %}
    {% load_article_metas article user %}
</article>

templates/blog/tags/article_meta_info.html
{% load blog_tags %}
<footer>
    本条发布于<a>
    <time class="entry-date updated"
          datetime="{{ article.created_time }}">
        {% datetimeformat article.created_time %}</time>
</a>

    {% if article.type == 'a' %}
        。属于{{ article.category.name }}
    {% endif %}
    {% if article.tags.all %}
        被贴了
        {% for t in article.tags.all %}
            {{ t.name }}
            {% if t != article.tags.all.last %}
                ,
            {% endif %}
        {% endfor %}
        标签
    {% endif %}
    <span>作者是
        {{ article.author.username }}
        {% if user.is_authenticated %}
            <a href="{{ article.get_admin_url }}">编辑</a>
        {% endif %}
    </span>

</footer>

templates/blog/tags/sidebar.html
<div id="secondary" class="widget-area">

    <form role="search" method="get" id="searchform" action="/search">
        <label>搜索:</label>
        <input type="text" value="" name="q" id="q">
        <input type="submit" id="searchsubmit" value="搜索">
    </form>
    {% if most_read_articles %}
        <aside>
            <h3>Views</h3>
            <ul>
                {% for a in most_read_articles %}
                    <li>
                        <a href="{{ a.get_absolute_url }}" title="{{ a.title }}">
                            {{ a.title }}
                        </a> - {{ a.views }} views

                    </li>
                {% endfor %}
            </ul>


        </aside>

    {% endif %}

    {% if sidebar_categorys %}
        <aside id="su_siloed_terms-2" class="widget widget_su_siloed_terms"><h3 class="widget-title">分类目录</h3>
            <ul>
                {% for c in sidebar_categorys %}
                    <li class="cat-item cat-item-184"><a href={{ c.get_absolute_url }}>{{ c.name }}</a>
                    </li>
                {% endfor %}
            </ul>
        </aside>
    {% endif %}
    {% if sidebar_comments %}
        <aside>
            <ul>
                {% for c in sidebar_comments %}
                    <li class="recentcomments">
                <span class="comment-author-link">
                    {{ c.author.username }}</span>
                        发表在《
                        <a href="{{ c.article.get_absolute_url }}">{{ c.article.title }}</a>》
                    </li>
                {% endfor %}

            </ul>
        </aside>

    {% endif %}
    {% if recent_articles %}
        <aside id="recent-posts-2" class="widget widget_recent_entries"><h3 class="widget-title">近期文章</h3>
            <ul>

                {% for a in  recent_articles %}
                    <li><a href="{{ a.get_absolute_url }}" title="{{ a.title }}">
                        {{ a.title }}
                    </a></li>
                {% endfor %}
            </ul>
        </aside>
    {% endif %}

    <aside id="meta-2" class="widget widget_meta"><h3 class="widget-title">功能</h3>
        <ul>
            <li><a href="{{ SITE_BASE_URL }}/admin/">管理站点</a></li>
            {% if user.is_authenticated %}
                <li><a href="{% url "account:logout" %}">登出</a>
                </li>

            {% else %}
                <li><a href="{% url "account:login" %}">登录</a>
            {% endif %}

        </ul>
    </aside>
<div id="rocket" class="show" title="点我返回顶部"></div>

</div>