blog/urls.py
#!/usr/bin/env python
# encoding: utf-8


from django.conf.urls import url, include
from . import views

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^article/(?P<year>\d+)/(?P<month>\d+)/(?P<day>\d+)/(?P<article_id>\d+).html$',
        views.ArticleDetailView.as_view(),
        name='detailbyid'),
    url(r'^category/(?P<category_name>[\w-]+).html$', views.CategoryDetailView.as_view(), name='category_detail'),
    url(r'^search', include('haystack.urls'), name='search')
]

comments/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^article/(?P<article_id>\d+)/postcomment$', views.CommentPostView.as_view(), name='postcomment'),
]

doudou_blog/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('blog.urls', namespace='blog', app_name='blog')),
    url(r'', include('comments.urls', namespace='comment', app_name='comments')),
    url(r'', include('accounts.urls', namespace='account', app_name='accounts')),

]

comments/models.py
from django.db import models
from django.conf import settings
from blog.models import Article
from django.contrib.sites.models import Site


# Create your models here.

class Comment(models.Model):
    body = models.TextField('正文', max_length=300)
    created_time = models.DateTimeField('创建时间', auto_now_add=True)
    last_mod_time = models.DateTimeField('修改时间', auto_now=True)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='作者', on_delete=models.CASCADE)
    article = models.ForeignKey(Article, verbose_name='文章', on_delete=models.CASCADE)
    parent_comment = models.ForeignKey('self', verbose_name='上级评论', blank=True, null=True)

    class Meta:
        ordering = ['created_time']
        verbose_name = '评论'
        verbose_name_plural = verbose_name
        get_latest_by = 'created_time'

    def send_comment_email(self, msg):
        try:
            msg.send()
        except:
            pass

    def __str__(self):
        return self.body

comments/forms.py
from .models import Comment
from django.forms import ModelForm
from django import forms


class CommentForm(ModelForm):
    url = forms.URLField(label='网址', required=False)
    email = forms.EmailField(label='电子邮箱', required=True)
    name = forms.CharField(label='姓名', widget=forms.TextInput(attrs=
                                                              {'value': "", 'size': "30", 'maxlength': "245",
                                                               'aria-required': 'true'}
                                                              ))
    parent_comment_id = forms.IntegerField(widget=forms.HiddenInput, required=False)

    class Meta:
        model = Comment
        fields = ['body']

comments/views.py
from django.views.generic.edit import FormView
from .forms import CommentForm
from .models import Comment
from django import forms
from blog.models import Article
from django.contrib.auth import get_user_model
from django.http import HttpResponseRedirect


# Create your views here.


class CommentPostView(FormView):
    form_class = CommentForm
    template_name = 'blog/article_detail.html'

    def form_valid(self, form):
        """提交的数据验证合法后的逻辑"""
        user = self.request.user

        article_id = self.kwargs['article_id']
        article = Article.objects.get(pk=article_id)

        if not self.request.user.is_authenticated():
            email = form.cleaned_data['email']
            username = form.cleaned_data['name']
            user = get_user_model().objects.get_or_create(username=username, email=email)[0]

        comment = form.save(False)
        comment.article = article
        comment.author = user

        if form.cleaned_data['parent_comment_id']:
            parent_comment = Comment.objects.get(pk=form.cleaned_data['parent_comment_id'])
            comment.parent_comment = parent_comment
        comment.save(True)

        return HttpResponseRedirect("%s#div-comment-%d" % (article.get_absolute_url(), comment.pk))

templates/comments/tags/comment_item.html
{% load blog_tags %}
<li id="comment-{{ comment_item.pk }}">
    <div id="div-comment-{{ comment_item.pk }}">
        <div>
            {{ comment_item.created_time }}
        </div>
        <p>{{ comment_item.body }}</p>
    </div>
    <div class="reply"><a rel="nofollow" class="comment-reply-link"
                          href="javascript:void(0)"
                          onclick="do_reply({{ comment_item.pk }})"
                          aria-label="回复给{{ comment_item.author.username }}">回复</a></div>

</li>

templates/comments/tags/comment_list.html
<section id="comments">
    {% load blog_tags %}
    {% load comment_tags %}
    <ul>
        <li>
            <a href="#commentlist-container">
                <i></i>评论<span>{{ comment_count }}</span>

            </a>
        </li>
    </ul>

    {% if article_comments %}
        <div id="commentlist-container">
            <ol>
                {% query article_comments parent_comment=None as parent_comments %}
                {% for comment in parent_comments %}
                    {% show_comment_item comment False %}
                    {% parse_commenttree article_comments comment as childcomments %}
                    {% if childcomments %}
                        <ul>
                            {% for child in childcomments %}
                                {% show_comment_item child True %}
                            {% endfor %}

                        </ul>
                    {% endif %}
                {% endfor %}

            </ol>

        </div>

    {% endif %}

</section>

templates/comments/tags/post_comment.html
<div id="comments">
    <div id="respond">
        <h3 id="reply-title" class="comment-reply-title">发表评论
            <small><a rel="nofollow" id="cancel-comment-reply-link" href="/wordpress/?p=3786#respond"
                      style="display:none;">取消回复</a></small>
        </h3>

        <form action="{% url 'comments:postcomment' article.pk %}" method="post" id="commentform">
            {% csrf_token %}
            <p>
                {{ form.body.label_tag }}

                {{ form.body }}
                {{ form.body.errors }}
            </p>

            <p>
                {% if not form.name.is_hidden %}
                    {{ form.name.label_tag }}
                {% endif %}
                {{ form.name }}
                {{ form.name.errors }}
                {% comment %}<label for="author">姓名 <span class="required">*</span></label>
                <input id="author" name="author" type="text" value="" size="30" maxlength="245" aria-required='true'
                       required='required'/></p>{% endcomment %}

            <p class="comment-form-email">
                {% comment %}    <label for="email">电子邮件 <span class="required">*</span></label> <input
                    id="email" name="email" type="text" value="" size="30" maxlength="100"
                    aria-describedby="email-notes" aria-required='true' required='required'/>{% endcomment %}
                {% if not form.email.is_hidden %}
                    {{ form.email.label_tag }}
                {% endif %}
                {{ form.email }}
                {{ form.email.errors }}
            </p>
            {% comment %}<p class="comment-form-url">
                {{ form.url.label_tag }}
                {{ form.url }}
                {{ form.url.errors }}

            </p>{% endcomment %}
            {{ form.parent_comment_id }}
            <p>
                <input name="submit" type="submit" id="submit" value="发表评论">
                <small id="cancel_comment" style="display: none">
                    <a href="javascript:void(0)" id="cancel-comment-reply-link" onclick="cancel_reply()">取消回复</a>
                </small>
            </p>
        </form>

    </div>

</div>